# Generated by Django 6.0.1 on 2026-01-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_enabled', models.BooleanField(default=True, help_text='Allow users to add new comments')),
            ],
            options={
                'verbose_name': 'Comment Settings',
                'verbose_name_plural': 'Comment Settings',
            },
        ),
    ]
